### ISSUE TITLE
Tempo command Fxx doesn't affect playback speed

### ISSUE THREAD

**Issue by tadashibashi** [stoneface86/trackerboy#14]
## Bug description

Using command Fxx doesn't affect playback speed–it only seems to be determined by the Trackerboy module's speed.

(Also, Trackerboy's playback speed doesn't seem to align with game boy emulators)

## How to reproduce

1. Type F04 into any channel effect column
2. Play song

## Information

 - OS: MacOS 12
 - Architecture: 64-bit, Apple Silicon M1
 - Trackerboy version: v0.6.2

**Comment by N-SPC700** [comment]
Command works as intended, relative to how Trackerboy handles speed. Speed in Trackerboy differs from that of other trackers like FamiTracker or Furnace, allowing more values in between the "standard" speed values.

F04 isn't valid, the lowest value that is valid is F10. This is because Trackerboy's fastest supported speed is 0x10 as indicated by the master speed setting.

Since you want "speed 4" as it would be in FamiTracker, use the command F40 instead of F04. This equates to setting the speed 0x40.

**Comment by tadashibashi** [comment]
Thanks, that answers the issue.

I'll open another one for emulators playing back at differing speeds from Trackerboy. It's significantly different, so I wonder what the issue is.
